# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5497c9c0bfdfca7860069e86a25fdd577c6f17206cd96c96d12a6ea8d3b979fd3dce6ce6b2b56d63f64d34b7ed9b0f260572a5cdc1b9c09f72a4d283cd842ccc

test:
  secret_key_base: fdc7ccdd319da6d163097a6c2ab58edd3eabaecc5db3b923eefca3bda9af5a05c0d6e456ef26f4771ac3e5dad55692708bcdb24c96e637e7b04c6795ceb69965

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
